### ISSUE TITLE
In the OSDR part, why s_k_target[k+1:].sum() is not s_k_target[k:].sum()?

### ISSUE THREAD

**Issue by LAKawai** [Cogito2012/OpenTAL#4]
In the AFSD/evaluation/utils_eval.py, the function 'open_set_detection_rate' calculates the osrd value. But why line 112 is CC = s_k_target[k+1:].sum(), but not CC = s_k_target[k:].sum(). I think >= current thresh should the positive.

**Comment by Cogito2012** [comment]
I guess it should not result in a big difference? This function is adapted from the implementation in [ARPL here](https://github.com/iCGY96/ARPL/blob/728eadb84c5ea799d1955e0c5b87aa6e9cc64a02/core/evaluation.py#L99)
