### ISSUE TITLE
Not able to download the RGB npy features

### ISSUE THREAD

**Issue by akshitac8** [Cogito2012/OpenTAL#5]
Hi, Thank you for sharing your amazing work. Can you please provide google drive link for the features ( thumos and ActivityNet).

**Comment by Cogito2012** [comment]
@akshitac8 Thanks for your interest in this work! 
I'll try to share them in an accessible folder these days, and let you know once they are ready.

**Comment by Cogito2012** [comment]
@akshitac8 As I do not have a huge personal remote storage, I uploaded the feature files (>300GB) to the university OneDrive folder. However, due to the sharing restriction of my university account, the link to those feature files can only be shared with your email account. You may double-check with your Gmail, or directly visit the [link](https://michiganstate-my.sharepoint.com/:f:/g/personal/baowenta_msu_edu/EpQW-dsyq45BpVnQpw3veqMBK4bt8tAWdSnjaT4SCHFvPg?email=akshita.sem.iitr%40gmail.com&e=4XuOYV).

Let me know if you encounter any questions.

**Comment by akshitac8** [comment]
Hi @Cogito2012 Thank you for uploading the features but activityNet features are getting stopped at 21 GB download. Can you please check if they are uploaded correctly from your side?

**Comment by Cogito2012** [comment]
@akshitac8 I checked the onedrive folder, and there are 14928 .npy files in the train_val_npy_112 folder.
I guess you're using webpage, you may try some command tool to download, for example, use the `rclone` and see the discussion here: [how-do-i-download-a-publicly-shared-onedrive-file](https://forum.rclone.org/t/how-do-i-download-a-publicly-shared-onedrive-file/33410)

**Comment by akshitac8** [comment]
Thank you for the help. @Cogito2012 Can you also please confirm if 
experiments/opental/train_opental_final.sh is correct? because some of the argparse are called in the train.py file.

**Comment by Cogito2012** [comment]
@akshitac8 It should be correct. 

Note that the complete arguments are in the `AFSD/common/config.py`, and the `train_opental_final.sh` will override the default args of the config.py. In the latter part of the config.py, args will be transformed into `data` variable, which is the `config` imported to `AFSD/thumos14/train.py`.

**Comment by akshitac8** [comment]
@Cogito2012 thank you so much for your help. I also wanted to ask, regarding the open set testing, In test_cross_data.sh under test_anet function. The testing is performed on  known classes of ActivityNet test data but I am not able to understand where do you perform testing on the data of the 5 unknown classes.

**Comment by Cogito2012** [comment]
@akshitac8 Note that because the model is only trained on thumos14, the classes from ActivitiyNet are all unknown (after excluding the overlapping classes). The testing codes are in `AFSD/thumos14/test_cross_data.py`.

**Comment by akshitac8** [comment]
Thank you for the help @Cogito2012. I have one last question, While training do you remove the videos containing unknown action instances?

**Comment by Cogito2012** [comment]
@akshitac8 I did not remove unknown video clips. That's why we say in the training, there exists "known unknown" actions, since the model could already see the unknown video clips but without training annotations.

**Comment by akshitac8** [comment]
Completed :)

**Comment by Anirudh257** [comment]
Hi @Cogito2012 could you share the features with me as well. I am unable to access the links for Thumos and ActivityNet here: https://share.weiyun.com/bP62lmHj and https://share.weiyun.com/PXXtHcbp

**Comment by Cogito2012** [comment]
> Hi @Cogito2012 could you share the features with me as well. I am unable to access the links for Thumos and ActivityNet here: https://share.weiyun.com/bP62lmHj and https://share.weiyun.com/PXXtHcbp

Sure, you should have access to this [link](https://michiganstate-my.sharepoint.com/:f:/g/personal/baowenta_msu_edu/EpQW-dsyq45BpVnQpw3veqMBK4bt8tAWdSnjaT4SCHFvPg) via your github Gmail account.
